
import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { ChevronDown, Eye, AlertTriangle, Package } from "lucide-react";
import { format } from "date-fns";
import { useProductionOrders } from "@/hooks/useProductionOrders";
import { validateStockForComponent } from "./StockValidator";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import ProductionVoucherDetails from "./ProductionVoucherDetails";

type BomType = "main_assembly" | "sub_assembly" | "accessory";

interface VoucherKitManagementProps {
  sentComponents: Record<string, string[]>;
  setSentComponents: React.Dispatch<React.SetStateAction<Record<string, string[]>>>;
  kitStatuses: Record<string, string>;
  setKitStatuses: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  voucherStatuses: Record<string, string>;
}

export default function VoucherKitManagement({ 
  sentComponents, 
  setSentComponents, 
  kitStatuses, 
  setKitStatuses,
  voucherStatuses 
}: VoucherKitManagementProps) {
  const { toast } = useToast();
  const { data: productionOrders } = useProductionOrders();
  const [selectedOrderForBOM, setSelectedOrderForBOM] = useState<any>(null);
  const [isBOMViewOpen, setIsBOMViewOpen] = useState(false);
  const [stockValidations, setStockValidations] = useState<Record<string, Record<string, boolean>>>({});

  // Check if component can be sent based on stock availability
  const canSendComponent = async (voucherId: string, component: string): Promise<boolean> => {
    const alreadySent = sentComponents[voucherId] || [];
    if (component !== "All Components" && alreadySent.includes(component)) {
      return false;
    }

    const productionOrder = productionOrders?.find(order => order.voucher_number === voucherId);
    if (!productionOrder) return false;

    const componentToBomType: Record<string, BomType> = {
      "Main Assembly": "main_assembly",
      "Sub Assembly": "sub_assembly",
      "Accessories": "accessory"
    };

    const bomType = componentToBomType[component];
    if (!bomType) return false;

    const validation = await validateStockForComponent(
      productionOrder.product_id, 
      productionOrder.quantity, 
      bomType
    );

    return validation.isValid;
  };

  // Handler for sending components with enhanced stock validation
  const handleSendComponent = async (voucherId: string, component: string) => {
    try {
      const canSend = await canSendComponent(voucherId, component);
      if (!canSend) {
        toast({
          title: "Insufficient Stock",
          description: "Insufficient stock to send kit. Please replenish before dispatch.",
          variant: "destructive",
        });
        return;
      }

      // Check if component has already been sent
      const alreadySent = sentComponents[voucherId] || [];
      if (component !== "All Components" && alreadySent.includes(component)) {
        toast({
          title: "Component Already Sent",
          description: `${component} has already been sent for this voucher`,
          variant: "destructive",
        });
        return;
      }

      // Find the production order
      const productionOrder = productionOrders?.find(order => order.voucher_number === voucherId);
      if (!productionOrder) {
        toast({
          title: "Error",
          description: "Production order not found",
          variant: "destructive",
        });
        return;
      }

      // Check if kit preparation already exists
      const { data: existingKit, error: checkError } = await supabase
        .from("kit_preparation")
        .select("*")
        .eq("production_order_id", productionOrder.id)
        .maybeSingle();

      if (checkError) throw checkError;

      let kitPrepId = existingKit?.id;

      // Create kit preparation record only if it doesn't exist
      if (!existingKit) {
        const { data: kitPrep, error: kitError } = await supabase
          .from("kit_preparation")
          .insert({
            production_order_id: productionOrder.id,
            status: "PREPARING",
            kit_number: "", // This will be auto-generated by the trigger
          })
          .select()
          .single();

        if (kitError) throw kitError;
        kitPrepId = kitPrep.id;
      }

      // Get BOM items for this product with component type filtering
      const { data: bomItems, error: bomError } = await supabase
        .from("bom")
        .select(`
          *,
          raw_materials!inner(*)
        `)
        .eq("product_id", productionOrder.product_id);

      if (bomError) throw bomError;

      // Map component names to BOM types
      const componentToBomType: Record<string, BomType> = {
        "Main Assembly": "main_assembly",
        "Sub Assembly": "sub_assembly",
        "Accessories": "accessory"
      };

      // Filter BOM items based on component type
      let filteredBomItems = bomItems;
      if (component !== "All Components") {
        const bomType = componentToBomType[component];
        if (bomType) {
          filteredBomItems = bomItems?.filter(item => item.bom_type === bomType) || [];
        }
      }

      if (!filteredBomItems || filteredBomItems.length === 0) {
        toast({
          title: "No Components Found",
          description: `No ${component} components found for this product`,
          variant: "destructive",
        });
        return;
      }

      // Check which items already exist in kit_items to avoid duplicates
      const { data: existingKitItems, error: existingError } = await supabase
        .from("kit_items")
        .select("raw_material_id")
        .eq("kit_preparation_id", kitPrepId);

      if (existingError) throw existingError;

      const existingRawMaterialIds = new Set(existingKitItems?.map(item => item.raw_material_id) || []);

      // Filter out items that already exist
      const newBomItems = filteredBomItems.filter(item => !existingRawMaterialIds.has(item.raw_material_id));

      // Create kit items for new components only
      if (newBomItems.length > 0) {
        const kitItems = newBomItems.map(bomItem => ({
          kit_preparation_id: kitPrepId,
          raw_material_id: bomItem.raw_material_id,
          required_quantity: bomItem.quantity * productionOrder.quantity,
          actual_quantity: bomItem.quantity * productionOrder.quantity, // Assuming full quantity is sent
        }));

        const { error: itemsError } = await supabase
          .from("kit_items")
          .insert(kitItems);

        if (itemsError) throw itemsError;
      }

      // Update sent components tracking
      const newSentComponents = component === "All Components" 
        ? ["Main Assembly", "Sub Assembly", "Accessories"]
        : [...alreadySent, component];

      setSentComponents(prev => ({
        ...prev,
        [voucherId]: newSentComponents
      }));

      // Determine new status based on what has been sent
      let newStatus = "";
      if (component === "All Components") {
        newStatus = "COMPLETE KIT SENT";
      } else {
        // Check if all components have been sent
        const allComponents = ["Main Assembly", "Sub Assembly", "Accessories"];
        const allSent = allComponents.every(comp => newSentComponents.includes(comp));
        
        if (allSent) {
          newStatus = "COMPLETE KIT SENT";
        } else if (newSentComponents.includes("Accessories") && newSentComponents.length === 1) {
          newStatus = "ACCESSORY COMPONENTS SENT";
        } else if (newSentComponents.includes("Sub Assembly") && newSentComponents.length === 1) {
          newStatus = "SUB ASSEMBLY COMPONENTS SENT";
        } else if (newSentComponents.includes("Main Assembly") && newSentComponents.length === 1) {
          newStatus = "MAIN ASSEMBLY COMPONENTS SENT";
        } else {
          // Multiple but not all components sent
          newStatus = "PARTIAL KIT SENT";
        }
      }

      // Update kit preparation status
      await supabase
        .from("kit_preparation")
        .update({ status: newStatus })
        .eq("id", kitPrepId);

      setKitStatuses(prev => ({
        ...prev,
        [voucherId]: newStatus
      }));

      toast({
        title: "Components Sent",
        description: `${component} has been sent to production for voucher ${voucherId}`,
      });

    } catch (error) {
      console.error("Error sending components:", error);
      toast({
        title: "Error",
        description: "Failed to send components to production",
        variant: "destructive",
      });
    }
  };

  // Check if component can be sent (synchronous version for UI)
  const canSendComponentSync = (voucherId: string, component: string) => {
    const alreadySent = sentComponents[voucherId] || [];
    if (component === "All Components") {
      return alreadySent.length === 0; // Can only send all if nothing has been sent
    }
    return !alreadySent.includes(component);
  };

  const getKitStatusColor = (status: string) => {
    switch (status) {
      case 'Ready': return 'default';
      case 'Not Ready': return 'destructive';
      case 'COMPLETE KIT SENT': return 'default';
      case 'ACCESSORY COMPONENTS SENT': return 'warning';
      case 'SUB ASSEMBLY COMPONENTS SENT': return 'warning';
      case 'MAIN ASSEMBLY COMPONENTS SENT': return 'warning';
      case 'PARTIAL KIT SENT': return 'warning';
      default: return 'secondary';
    }
  };

  const handleViewProductionVoucher = (order: any) => {
    setSelectedOrderForBOM(order);
    setIsBOMViewOpen(true);
  };

  return (
    <>
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Package className="h-5 w-5" />
            Voucher & Kit Management ({productionOrders?.length || 0})
          </CardTitle>
        </CardHeader>
        <CardContent>
          {productionOrders?.length ? (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Voucher No.</TableHead>
                  <TableHead>Product Name</TableHead>
                  <TableHead>Scheduled Production Date</TableHead>
                  <TableHead>Quantity</TableHead>
                  <TableHead>Voucher Status</TableHead>
                  <TableHead>Send Components</TableHead>
                  <TableHead>Production Voucher</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {productionOrders.map((order) => (
                  <TableRow key={order.id}>
                    <TableCell className="font-mono">{order.voucher_number}</TableCell>
                    <TableCell className="font-medium">
                      {order.production_schedules?.projections?.products?.name}
                    </TableCell>
                    <TableCell>{format(new Date(order.scheduled_date), 'MMM dd, yyyy')}</TableCell>
                    <TableCell>{order.quantity}</TableCell>
                    <TableCell>
                      <Badge variant={getKitStatusColor(voucherStatuses[order.voucher_number] || "Unknown") as any}>
                        {voucherStatuses[order.voucher_number] || "Loading..."}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="outline" size="sm" className="gap-2">
                            Send Components
                            <ChevronDown className="h-4 w-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          {["Sub Assembly", "Accessories", "Main Assembly"].map((component) => {
                            const isAlreadySent = !canSendComponentSync(order.voucher_number, component);
                            const voucherKey = `${order.voucher_number}-${component}`;
                            const hasStock = stockValidations[voucherKey];
                            
                            return (
                              <DropdownMenuItem 
                                key={component}
                                onClick={() => !isAlreadySent && handleSendComponent(order.voucher_number, component)}
                                disabled={isAlreadySent}
                                className={!hasStock && !isAlreadySent ? "text-red-600" : ""}
                              >
                                <div className="flex items-center gap-2">
                                  {!hasStock && !isAlreadySent && <AlertTriangle className="h-4 w-4" />}
                                  Send {component}
                                  {isAlreadySent && " (Already Sent)"}
                                  {!hasStock && !isAlreadySent && " (Insufficient Stock)"}
                                </div>
                              </DropdownMenuItem>
                            );
                          })}
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                    <TableCell>
                      <Button 
                        variant="outline" 
                        size="sm" 
                        className="gap-2"
                        onClick={() => handleViewProductionVoucher(order)}
                      >
                        <Eye className="h-4 w-4" />
                        Production Voucher
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              No production vouchers found
            </div>
          )}
        </CardContent>
      </Card>

      <ProductionVoucherDetails
        isOpen={isBOMViewOpen}
        onClose={() => {
          setIsBOMViewOpen(false);
          setSelectedOrderForBOM(null);
        }}
        productionOrder={selectedOrderForBOM}
        onComponentSent={(component) => {
          if (selectedOrderForBOM) {
            handleSendComponent(selectedOrderForBOM.voucher_number, component);
          }
        }}
        sentComponents={selectedOrderForBOM ? sentComponents[selectedOrderForBOM.voucher_number] || [] : []}
      />
    </>
  );
}
