-- Products from Anmol's GRAMMY_PLM_Tracker.xlsx (as shared, 1 Oct 2026), plus the two finished goods
-- already in production before the ERP. Imported with their stage, checklist states and issues.
SELECT set_config('app.plm','on',true);
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('SB22P','Philips TAB5304','Soundbar','NEW_MODEL','GRAMMY','Philips','ODM','HIGH',NULL,'2026-08-24',2,'LETTER_RECEIVED',NULL);
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB22P' AND d.key='crs_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB22P' AND d.key='did';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB22P' AND d.key='bom_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB22P' AND d.key='proto1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB22P' AND d.key='sound_test';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB22P' AND d.key='cost_conf';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB22P' AND d.key='proto2';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,1,'IMPORTED','From the PLM tracker' FROM public.plm_products WHERE product_code='SB22P';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('SB24C','Croma 180W Dolby SB','Soundbar','VARIATION','GRAMMY','Croma','ODM','HIGH','2026-07-09','2026-08-25',1,'NOT_STARTED',NULL);
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='crs_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='did';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='bom_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='proto1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='sound_test';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='cost_conf';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='proto2';
UPDATE public.plm_deliverables d SET status='OPEN' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='eng_issues';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='bom_picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='wi_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='oqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='pqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='fw_freeze';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='pp_build';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='wi_validated';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='qc_executed';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='yield_ok';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='packaging';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='jigs';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='issue_list';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='ort_plan';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB24C' AND d.key='customer_pp_exit';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('J6C','Philips TAX2304','Party Speaker','NEW_MODEL','GRAMMY','Philips','ODM','HIGH','2026-06-05','2026-08-11',4,'LETTER_RECEIVED',NULL);
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='crs_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='did';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='bom_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='proto1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='sound_test';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='cost_conf';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='proto2';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='bom_v2';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='eng_issues';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6C' AND d.key='fw_freeze';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,1,'IMPORTED','From the PLM tracker' FROM public.plm_products WHERE product_code='J6C';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,2,'IMPORTED','From the PLM tracker' FROM public.plm_products WHERE product_code='J6C';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,3,'IMPORTED','From the PLM tracker' FROM public.plm_products WHERE product_code='J6C';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('J9','Party Speaker 40W','Party Speaker','NEW_MODEL','GRAMMY',NULL,'ODM','MEDIUM','2026-06-15','2026-11-01',1,'NOT_STARTED',NULL);
UPDATE public.plm_deliverables d SET status='WIP' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J9' AND d.key='crs_v1';
UPDATE public.plm_deliverables d SET status='OPEN' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J9' AND d.key='did';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J9' AND d.key='proto1';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('SB11C','Croma 120W Soundbar','Soundbar','VARIATION','GRAMMY','Croma','ODM','MEDIUM',NULL,NULL,1,'NOT_STARTED',NULL);
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='crs_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='did';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='proto1';
UPDATE public.plm_deliverables d SET status='WIP' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='sound_test';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='cost_conf';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='proto2';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='bom_picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='wi_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='oqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='pqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='fw_freeze';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='pp_build';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='wi_validated';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='qc_executed';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='yield_ok';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='packaging';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='jigs';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='issue_list';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='ort_plan';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB11C' AND d.key='customer_pp_exit';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('J10','Party speaker 55W','Party Speaker','NEW_MODEL','GRAMMY',NULL,'ODM','MEDIUM','2026-07-19','2026-11-01',1,'NOT_STARTED',NULL);
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('J4D','D-1365','Party Speaker','VARIATION','GRAMMY','Digimore','ODM','HIGH','2026-06-19','2026-08-15',1,'LETTER_RECEIVED',NULL);
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='crs_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='did';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='bom_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='proto1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='sound_test';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='cost_conf';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='proto2';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='bom_picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='wi_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='oqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='pqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='fw_freeze';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='pp_build';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='wi_validated';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='qc_executed';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='yield_ok';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='packaging';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='jigs';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='issue_list';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='ort_plan';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4D' AND d.key='customer_pp_exit';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('SB06D','DHT-2101','Soundbar','NEW_MODEL','GRAMMY','Digimore','ODM','HIGH','2026-06-19','2026-08-15',1,'LETTER_RECEIVED',NULL);
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB06D' AND d.key='did';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB06D' AND d.key='bom_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB06D' AND d.key='proto1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB06D' AND d.key='sound_test';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='SB06D' AND d.key='proto2';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('J4SM','Stage +','Party Speaker','VARIATION','GRAMMY','Swiss Military',NULL,'MEDIUM',NULL,NULL,1,'NOT_STARTED',NULL);
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='crs_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='did';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='proto1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='cost_conf';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='proto2';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='bom_picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='wi_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='oqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='pqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='fw_freeze';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='pp_build';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='wi_validated';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='qc_executed';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='yield_ok';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='packaging';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='jigs';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='issue_list';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='ort_plan';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J4SM' AND d.key='customer_pp_exit';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('J6SM','Battalion','Party Speaker','VARIATION','GRAMMY','Swiss Military',NULL,'MEDIUM',NULL,NULL,1,'NOT_STARTED',NULL);
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='crs_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='did';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='proto1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='cost_conf';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='proto2';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='bom_picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='picture_book';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='wi_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='oqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='pqc_v1';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='fw_freeze';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='pp_build';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='wi_validated';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='qc_executed';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='yield_ok';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='packaging';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='jigs';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='issue_list';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='ort_plan';
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='J6SM' AND d.key='customer_pp_exit';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('F14F','Heera 8 Pro max','Party Speaker','NEW_MODEL','CLIENT','FlowBeats',NULL,'MEDIUM',NULL,NULL,1,'NOT_STARTED',NULL);
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('J11','Explode 3.0','Party Speaker','NEW_MODEL','GRAMMY','Croma',NULL,'MEDIUM',NULL,NULL,1,'NOT_STARTED',NULL);
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('J12','Partyspeaker 120W','Party Speaker','NEW_MODEL','GRAMMY',NULL,NULL,'MEDIUM',NULL,NULL,1,'NOT_STARTED',NULL);
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('J13','Croma 80W PartySpeaker','Party Speaker','NEW_MODEL','GRAMMY','Croma',NULL,'MEDIUM',NULL,NULL,1,'NOT_STARTED',NULL);
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,business_model,priority,start_date,target_launch,stage,bis_status,notes) VALUES ('M2SM','Upraoar Wireless mic','Microphone','NEW_MODEL','GRAMMY','Swiss Military',NULL,'MEDIUM',NULL,NULL,1,'NOT_STARTED',NULL);
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,priority,stage,bis_status,notes) VALUES ('JA-006','PHILIPS TAX 2504/94','Party Speaker','NEW_MODEL','GRAMMY','Philips','MEDIUM',6,'LETTER_RECEIVED','In production before the ERP started; imported at mass production.');
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='JA-006';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,1,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='JA-006';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,2,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='JA-006';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,3,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='JA-006';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,4,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='JA-006';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,5,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='JA-006';
INSERT INTO public.plm_products (product_code,name,category,kind,ownership,client,priority,stage,bis_status,notes) VALUES ('MI-001','CREA001DJA260103','Microphone','NEW_MODEL','GRAMMY','Croma','MEDIUM',6,'LETTER_RECEIVED','In production before the ERP started; imported at mass production.');
UPDATE public.plm_deliverables d SET status='CLOSED' FROM public.plm_products p WHERE p.id=d.product_id AND p.product_code='MI-001';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,1,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='MI-001';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,2,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='MI-001';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,3,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='MI-001';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,4,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='MI-001';
INSERT INTO public.plm_gates (product_id,gate,how,note) SELECT id,5,'IMPORTED','In production before the ERP' FROM public.plm_products WHERE product_code='MI-001';
UPDATE public.parts SET plm_product_id=(SELECT id FROM public.plm_products WHERE product_code='J6C') WHERE part_code='JA-06C-PH';
UPDATE public.parts SET plm_product_id=(SELECT id FROM public.plm_products WHERE product_code='M2SM') WHERE part_code='MI-002-SM';
UPDATE public.parts SET plm_product_id=(SELECT id FROM public.plm_products WHERE product_code='JA-006') WHERE part_code='JA-006-PH';
UPDATE public.parts SET plm_product_id=(SELECT id FROM public.plm_products WHERE product_code='MI-001') WHERE part_code='MI-001-CR';
INSERT INTO public.plm_issues (issue_no,product_id,stage,raised_on,description,severity,owner,action,target_date,status,closed_on,remarks,source) SELECT 'ISS-001',id,3,coalesce('2026-08-03'::date,current_date),'Pair is displayed on screen when we disconnect BT from Panel keys','HIGH','OTK',NULL,NULL,'OPEN',NULL,NULL,'IMPORTED' FROM public.plm_products WHERE product_code='SB24C';
SELECT setval('public.seq_plm_issue', greatest(1,(SELECT max(substring(issue_no from 5)::int) FROM public.plm_issues)));
SELECT set_config('app.plm','',true);
SELECT public.plm_refresh_all();
