
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oacdhvmpkuadlyvvvbpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hY2Rodm1wa3VhZGx5dnZ2YnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0Mzg4NzMsImV4cCI6MjA2NDAxNDg3M30.PwYMVaaKCAS9caTilNiLr2_xyOXty3t93FQ8O-JvAAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'supabase.auth.token',
    debug: false
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web'
    }
  }
});

// Add error handling for auth state changes
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED' && !session) {
    console.warn('Token refresh failed, session cleared');
  }
  if (event === 'SIGNED_OUT') {
    console.log('User signed out, clearing local data');
  }
});
