// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kowlnobjbzdhuhcwghkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvd2xub2JqYnpkaHVoY3dnaGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjI4MDIsImV4cCI6MjA2MzEzODgwMn0.Pi8PrZzUFgZMkvyJxckYf75ApyLM0nd1d0t4RDSxm6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);